[project]
name = "tjbots"
version = "0.1.0"
description = "TJ's adventures with LLMs"
readme = "README.md"
license = "AGPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.58.2",
    "chatlas>=0.9.1",
    "google-genai>=1.26.0",
    "openai>=1.97.1",
    "python-dotenv>=1.1.1",
    "shiny>=1.4.0",
]

[project.urls]
Homepage = "https://github.com/tjpalanca/tjbots"
Repository = "https://github.com/tjpalanca/tjbots"
Issues = "https://github.com/tjpalanca/tjbots/issues"
