project:
  type: website
  post-render: 
    - scripts/copy_readme.py
  
execute: 
  freeze: true

website:
  title: "TJBots"
  navbar:
    logo: images/tjbots.svg
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - section: Development
        contents:
        - href: 00-general.qmd
        - href: 01-chatbot.qmd
      - section: Scenarios 
        contents:
        - href: 01-grocerybot.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
