name: Setup docker
description: "setup Docker build environment with QEMU, Buildx, and GitHub Container Registry login"
inputs:
  github-token:
    description: 'GitHub token for container registry authentication'
    required: true
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
