project:
  type: website
  post-render: 
    - scripts/copy_readme.py

resources: 
  - assets/**

execute:
  enabled: false

website:
  title: "TJBots"
  repo-url: https://github.com/tjpalanca/tjbots
  repo-subdir: docs
  favicon: assets/logo/tjbots.svg
  navbar:
    search: true
  sidebar:
    contents: auto

format:
  html:
    license: "CC BY"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

quartodoc:
  title: Reference
  package: tjbots
  parser: google
  source_dir: ../src/tjbots
  sections:
    - title: Bots Playground
      package: tjbots.app
      desc: |-
        Chatbot application that facilitates testing of various 
        combinations of bots, tools, and other configuration.
      contents:
        - app
    - subtitle: Modules
      package: tjbots.app.modules
      contents:
        - pwa
        - reconnect
