on:
  workflow_dispatch:
  push:
    branches: main

name: Publish Application Image

jobs:
  notes-publish:
    name: Publish application to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push application image
        run: make app-push