on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "pyproject.toml"
      - "uv.lock"

name: Publish Application Image

jobs:
  app-publish:
    name: Publish application image to GitHub Container Registry
    strategy:
      matrix:
        include:
          - os: ubuntu-latest         
          - os: ubuntu-22.04-arm      
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push application image (${{ matrix.os }})
        run: make app-push
