on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "notes/**"

name: Publish Notes

jobs:
  notes-publish:
    name: Publish Notes to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
