on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/tjbots-test.yml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"
      - "uv.lock"

name: Test TJBots

jobs:
  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('uv.lock') }}

      - name: Install dependencies
        run: make deps
        
      - name: Run tests
        run: make test
